# Pytorch

¿Qué es pytorch?

Pytorch es una biblioteca cuyo principal objetvio es agilizar las operaciones que vemos comunmente en Numpy. Esto lo logra ya que en un programa normal de Numpy este se ejecuta en su totalidad en el CPU de nuestra computadora, pytorch busca agilizar el calculo de varias operaciones usando CUDA cores, el cual es un tipo de arquitecttura implementado en las por la compañia Nvidia en su linea de tarjetas graficas o GPU's

¿Tiene sentido usar Pytorch si no tengo un GPU nvida?

Para este curso si, esto debido a que pytorch tiene un implementación robusta para la construcción de diferentes arquitecturas de redes neuronales, tiene una variedad de método de entrenamiento y en general facilita el manejo de  una red neuronal.

Nota: En caso de no tener un GPU Nvidia el programa simplemente se ejecutara en nuestro CPU


## Tensor

Un tensor es la estructura mas importante que nos brinda Pytorch. ¿Qué es un tensor?

Un tensor lo podemos ver como un arreglo de numpy, de hecho podemos decir que funcionan de similar, con una gran diferencia, los tensores pueden realizar sus operaciones haciendo uso de un la arquitectura CUDA, mientras que las operaciones con arreglos de Numpy generalemnte se realizan en nuestro CPU

In [15]:
# Importamos el paquete de pytorch

import torch

# Inicializacion de un tensor

#Para inicia un tensor tenemos una amplia variedad de comandos, en el siguiente ejemplo creamos un tensor
#  de dimension 2X4

x = torch.empty(2, 4)
print(x)

#En en el ejemplo anterior simplemente estamos declarando que x es un tensor de dimension 2x4, pero el tensor
#no ha sido inicializado, en este caso pytorch simplemente imprime los valores que se encuentran en la memoria

# Para crear un tensor de dimension 2x4 con valores aleatorios
x = torch.rand(2, 4)
print("Tensor usando rand()")
print(x)


# Creamos un tensor de puros ceros, donde cada entrada es de tipo número punto flotante
x = torch.zeros(2, 4, dtype=torch.float)
print("Tensor usando zeros()")
print(x)

#Nota: Por lo general los metodos que conocen para crear arreglos de numpy, tienen un homonimo en pytorch

#Tambien podemos crear tensores a partir de listas

x = torch.tensor([3.14, 2.75])
print("Tensor usando una lista")
print(x)

#Para obtener las dimensiones de nuestro tensor
print("Tamaño")
print(x.size())


tensor([[6.0297e-16, 4.5839e-41, 6.0297e-16, 4.5839e-41],
        [4.4842e-44, 0.0000e+00, 1.5695e-43, 0.0000e+00]])
Tensor usando rand()
tensor([[0.8151, 0.3719, 0.4234, 0.4354],
        [0.2480, 0.3946, 0.6242, 0.3195]])
Tensor usando zeros()
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])
Tensor usando una lista
tensor([3.1400, 2.7500])
Tamaño
torch.Size([2])


## Operaciones de Tensor

In [23]:
#En cuanto operaciones basicas aritmeticas de tensores funcionan igual que las operaciones de arreglos de numpy

x=torch.rand((6,3))
print(x)

#Sumamos,restar,multiplicar,dividir un escalar a todos los valores de nuetro tensor

print("Sumar escalar 5")
print(x + 5)

print("Restar escalar 5")
print(x - 5)


print("multiplicar escalar 5")
print(x * 5)


print("Dividir escalar 5")
print(x / 5)


# De la misma forma las operaciones entre dos tensores entrada por entrada

print("\nOperacion entre dos tensores")
y = torch.rand((6,3))
print(y)

print("Sumar5")
print(x + y)

print("Restar")
print(x - y)


print("multiplicar")
print(x * y)


print("Dividir")
print(x / y)


tensor([[0.4747, 0.6403, 0.1310],
        [0.4027, 0.7530, 0.3021],
        [0.8889, 0.5031, 0.5241],
        [0.2573, 0.4944, 0.0839],
        [0.8437, 0.6687, 0.2242],
        [0.0506, 0.1619, 0.9607]])
Sumar escalar 5
tensor([[5.4747, 5.6403, 5.1310],
        [5.4027, 5.7530, 5.3021],
        [5.8889, 5.5031, 5.5241],
        [5.2573, 5.4944, 5.0839],
        [5.8437, 5.6687, 5.2242],
        [5.0506, 5.1619, 5.9607]])
Restar escalar 5
tensor([[-4.5253, -4.3597, -4.8690],
        [-4.5973, -4.2470, -4.6979],
        [-4.1111, -4.4969, -4.4759],
        [-4.7427, -4.5056, -4.9161],
        [-4.1563, -4.3313, -4.7758],
        [-4.9494, -4.8381, -4.0393]])
multiplicar escalar 5
tensor([[2.3733, 3.2017, 0.6552],
        [2.0135, 3.7650, 1.5107],
        [4.4443, 2.5156, 2.6206],
        [1.2867, 2.4718, 0.4194],
        [4.2184, 3.3436, 1.1209],
        [0.2530, 0.8094, 4.8036]])
Dividir escalar 5
tensor([[0.0949, 0.1281, 0.0262],
        [0.0805, 0.1506, 0.0604],
        [0.1778, 0.10

Notemos que en los ejemplos anteriores el tensor x nunca es modificado, es decir, operaciones tipo x + 5 nos regresan un nuevo tensor resultado de esa operacion, dejando intacto al tensor x.

Si queremos modificar directamente x, se puede recurrir a llamar a las funciones correpondientes a las operaciones con un _ al final.

In [24]:
print("Tensor original x")
print(x)
print("\nSumanos 5")
x.add_(5)
print(x)

print("\n Restamos 5")
x.add_(-5)
print(x)

print("\nSumanos tensor y")
x.add_(y)
print(x)

Tensor original x
tensor([[0.4747, 0.6403, 0.1310],
        [0.4027, 0.7530, 0.3021],
        [0.8889, 0.5031, 0.5241],
        [0.2573, 0.4944, 0.0839],
        [0.8437, 0.6687, 0.2242],
        [0.0506, 0.1619, 0.9607]])

Sumanos 5
tensor([[5.4747, 5.6403, 5.1310],
        [5.4027, 5.7530, 5.3021],
        [5.8889, 5.5031, 5.5241],
        [5.2573, 5.4944, 5.0839],
        [5.8437, 5.6687, 5.2242],
        [5.0506, 5.1619, 5.9607]])

 Restamos 5
tensor([[0.4747, 0.6403, 0.1310],
        [0.4027, 0.7530, 0.3021],
        [0.8889, 0.5031, 0.5241],
        [0.2573, 0.4944, 0.0839],
        [0.8437, 0.6687, 0.2242],
        [0.0506, 0.1619, 0.9607]])

Sumanos tensor y
tensor([[0.7170, 1.3524, 0.8437],
        [0.4916, 1.1865, 0.4921],
        [1.0757, 1.1916, 0.5419],
        [0.3835, 0.9728, 0.9524],
        [1.8020, 1.0221, 0.9416],
        [0.9864, 1.1491, 1.0426]])


## Tensor y Numpy


Otra facilidad que nos brinda tenserflow es la facilidad para pasar un arreglo de numpy a un tensor y para pasar
un tensor a un arreglo de numpy

In [39]:
import numpy as np

#Pasamos un tensor a un arreglo de numpy


x = torch.ones((12,4))
print("Tensor")
print(x)

print("\nArreglo numpy")
y = x.numpy()
print(y)


# Arreglo de numpy a tensor
x = np.ones((8,4))
print("\nArreglo numpy")
print(x)


y = torch.from_numpy(x)
print("\nTensor")
print(y)


Tensor
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

Arreglo numpy
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Arreglo numpy
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Tensor
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)


Algo importante que debemos notar de este método es que cualquier modificación que realizan al tensor orginal o
al arreglo original de numpy, tambien afectara al arreglo o tensor correspondiente. Esto solo sucede cuando se 
esta usando el CPU para realizar las operaciones y no un GPU

In [40]:
print("\nArreglo numpy ")
print(x)

print("\nTensor correspondiente")
print(y)

print("\nSumamos el escalar 5 al arreglo de numpy")
np.add(x, 1, out=x)
print(x)

print("\nLos cambios también se efectuan de forma automatica en nuestro tensor asociado")
print(y)


Arreglo numpy 
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Tensor correspondiente
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)

Sumamos el escalar 5 al arreglo de numpy
[[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]

Los cambios también se efectuan de forma automatica en nuestro tensor asociado
tensor([[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]], dtype=torch.float64)
